CFLAGS = -Wall -std=gnu99 -pthread

main_v1: main_v1.c
	gcc $(CFLAGS) -o main_v1 main_v1.c

main_v2: main_v2.c
	gcc $(CFLAGS) -o main_v2 main_v2.c

main_v3: main_v3.c
	gcc $(CFLAGS) -o main_v1 main_v3.c

main_v4: main_v4.c
	gcc $(CFLAGS) -o main_v4 main_v4.c

main_v5: main_v5.c
	gcc $(CFLAGS) -o main_v5 main_v5.c

main_v6: main_v6.c
	gcc $(CFLAGS) -o main_v6 main_v6.c

clean:
	rm -f main_v1 main_v2 main_v3 main_v4 main_v5 main_v6
